version: '3.8'

services:
  nextjs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - redis
    command: npm run dev -- -H 0.0.0.0  # ← Adicione -H 0.0.0.0 aqui
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "24731:24731"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # ← Use o arquivo corrigido
      - ./cert:/etc/nginx/cert:ro
    depends_on:
      - nextjs-app
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge